-- Lakeflow Declarative Pipeline — batch agent inference via ai_query()
--
-- Plan reference: agent-designer-deployment.md Section F.2 (Lakeflow + SQL primary path).
--
-- Critical: pipelines.channel = 'preview' is REQUIRED — the `current` channel
-- runtime does not include ai_query (the call fails with "function not found").
-- Both this SQL and the DAB resources.pipelines.<name>.channel field must agree.
--
-- This template is rendered by BatchTranslator.translate(); the placeholders
-- below are str.format-substituted at deploy time. Endpoint and table names
-- are validated at the API layer (Pydantic) before render.
--
-- Decoupled from Mode 3 (plan Section F.1): {endpoint_name} may be a Mode 3
-- deployment name OR any pre-existing serving endpoint in the workspace.

CREATE OR REFRESH MATERIALIZED VIEW {output_table_quoted}
TBLPROPERTIES (pipelines.channel = 'preview')
COMMENT 'Per-row agent inference output. Generated by Agent Designer batch deployment.'
AS SELECT
  *,
  ai_query(
    '{endpoint_name}',
    {prompt_column_quoted}{response_format_clause},
    failOnError => false
  ) AS agent_response
FROM {input_table_quoted};
