"""Shell-app FastAPI entry point.

Generated by ``ShellAppExporter``. Renders a minimal chat UI bound to one
``WorkflowDefinition`` AST embedded at deploy time. The framework is
pip-installed via the Git tag pin in ``pyproject.toml`` (no PyPI yet).

Plan reference: agent-designer-deployment.md Section E.5.
"""
from __future__ import annotations

import asyncio
import inspect
import json
import logging
import os
import time
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import uuid4

import mlflow
import yaml
from databricks.sdk import WorkspaceClient
from databricks_deep_research import (
    FrameworkLLMClient,
    ToolFactoryContext,
    WorkflowRunner,
    build_databricks_workflow_runner,
    workflow_requires_databricks,
)
from databricks_deep_research.surface import (
    build_pending_envelope,
    build_structured_envelope,
    collect_output_slots,
    inject_structured_output_contract,
    resolve_binding_for_run,
)
from databricks_deep_research.events.types import ToolResultEvent
from databricks_deep_research.tools.builtins.text_table import (
    wire_statement_execution_text_table_context,
)
from databricks_deep_research.tracing import setup_mlflow_tracing
from databricks_deep_research.workflow.loader import load_workflow_from_dict
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from sse_starlette.sse import EventSourceResponse

# Feature-detect optional kwargs on WorkflowRunner.stream so this template
# remains forward/back-compatible with frameworks that don't yet expose them.
# Older databricks-deep-research releases did not accept `strict_tool_resolution`;
# passing it unconditionally would raise `TypeError` at runtime.
try:
    _STREAM_PARAMS: set[str] = set(inspect.signature(WorkflowRunner.stream).parameters)
except (TypeError, ValueError):  # pragma: no cover - defensive
    _STREAM_PARAMS = set()
_SUPPORTS_STRICT_TOOL_RESOLUTION: bool = "strict_tool_resolution" in _STREAM_PARAMS


def _classify_traceback_modules(exc: BaseException) -> list[str]:
    """Return module names appearing in the exception's traceback frames.

    Used by :func:`_classify_shell_app_exception` to detect ``TypeError`` /
    ``AttributeError`` that originated inside the framework call chain
    (rather than user code). Defensive: returns an empty list on any
    introspection failure so classifier never raises.
    """
    try:
        tb = exc.__traceback__
        modules: list[str] = []
        while tb is not None:
            frame_module = tb.tb_frame.f_globals.get("__name__", "")
            if isinstance(frame_module, str):
                modules.append(frame_module)
            tb = tb.tb_next
        return modules
    except Exception:  # pragma: no cover - defensive
        return []


def _classify_shell_app_exception(exc: BaseException) -> str:
    """Bucket runtime exceptions so the UI can render actionable next-steps.

    Categories (Phase 3 M4):

    * ``workflow_error`` — framework refused to start or aborted the
      workflow (missing tools under strict mode, schema violations, etc.).
      User action: redesign or re-deploy the agent with corrected config.
    * ``framework_skew`` — call into framework code failed with a
      ``TypeError`` / ``AttributeError`` because the installed framework
      version doesn't match the template's expected API surface. User
      action: redeploy with an updated ``framework_git_tag``.
    * ``runtime_error`` — anything else (network, LLM, generic Python).
      User action: retry or contact support.

    The classifier is intentionally narrow: only catches well-known
    framework-side exception types. Anything we don't recognize stays as
    ``runtime_error`` so the user gets the raw message + class name.
    """
    if type(exc).__name__ == "WorkflowError":
        return "workflow_error"
    module = getattr(type(exc), "__module__", "") or ""
    if isinstance(exc, (TypeError, AttributeError)) and (
        "databricks_deep_research" in module
        or "databricks_deep_research" in "".join(_classify_traceback_modules(exc))
    ):
        return "framework_skew"
    return "runtime_error"

_LOG_LEVEL_NAME = os.environ.get("LOG_LEVEL", "INFO").upper()
_LOG_LEVEL = getattr(logging, _LOG_LEVEL_NAME, logging.INFO)
logging.basicConfig(
    level=_LOG_LEVEL,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logging.getLogger().setLevel(_LOG_LEVEL)
logger = logging.getLogger(__name__)
logger.setLevel(_LOG_LEVEL)
_SHELL_APP_TEMPLATE_VERSION = "2026-05-28.1"
_NO_STORE_HEADERS = {
    "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
    "Pragma": "no-cache",
    "Expires": "0",
    "X-Shell-App-Template-Version": _SHELL_APP_TEMPLATE_VERSION,
}


def _env_flag(name: str, *, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, *, default: int, minimum: int) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        value = int(raw)
    except ValueError:
        logger.warning(
            "SHELL_APP_INVALID_INT_ENV name=%s value=%r default=%s",
            name,
            raw,
            default,
        )
        return default
    if value < minimum:
        logger.warning(
            "SHELL_APP_INVALID_INT_ENV name=%s value=%s minimum=%s default=%s",
            name,
            value,
            minimum,
            default,
        )
        return default
    return value


# ── MLflow tracing setup ─────────────────────────────────────────────────
# Shell-app MLflow tracing is opt-in because trace artifact export can block
# long-lived SSE streams when Databricks storage is unreachable from the app.
# When enabled, provenance is sourced from the DR_* env vars Jinja-interpolated
# by the ShellAppExporter at deploy time.

_MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "databricks")
_MLFLOW_EXPERIMENT_NAME = os.environ.get(
    "MLFLOW_EXPERIMENT_NAME", "/Shared/deep-research-agent-experiments"
)
_DR_APP_NAME = os.environ.get("DR_APP_NAME", "")
_DR_AGENT_V2_ID = os.environ.get("DR_AGENT_V2_ID", "")
_DR_AGENT_NAME = os.environ.get("DR_AGENT_NAME", "")
_DR_REVISION_ID = os.environ.get("DR_REVISION_ID", "")
_MLFLOW_ENABLED = _env_flag("MLFLOW_ENABLED", default=False)
_SSE_HEARTBEAT_SECONDS = _env_int(
    "SHELL_APP_SSE_HEARTBEAT_SECONDS",
    default=15,
    minimum=5,
)

if _MLFLOW_ENABLED:
    try:
        setup_mlflow_tracing(
            tracking_uri=_MLFLOW_TRACKING_URI,
            experiment_name=_MLFLOW_EXPERIMENT_NAME,
        )
        logger.info(
            "SHELL_APP_MLFLOW_TRACING_INITIALIZED tracking_uri=%s experiment=%s "
            "app_name=%s agent_v2_id=%s revision_id=%s",
            _MLFLOW_TRACKING_URI, _MLFLOW_EXPERIMENT_NAME,
            _DR_APP_NAME, _DR_AGENT_V2_ID, _DR_REVISION_ID,
        )
    except Exception as exc:  # pragma: no cover - tracing must never fail boot
        logger.warning("SHELL_APP_MLFLOW_TRACING_INIT_FAILED exc=%s", exc)
else:
    logger.info(
        "SHELL_APP_MLFLOW_TRACING_DISABLED mlflow_enabled_env=%r",
        os.environ.get("MLFLOW_ENABLED"),
    )


def _set_dr_provenance_tags(query: str, workflow_id: str, workflow_name: str) -> None:
    """Tag the current MLflow trace with dr.* provenance fields.

    Mirrors ``deep_research.core.trace_provenance.set_trace_provenance`` —
    duplicated here because the shell-app template is shipped without a
    dependency on the main app's package. Safe to call when mlflow has no
    active trace; failures are swallowed (tracing is best-effort).
    """
    if not _MLFLOW_ENABLED:
        return
    tags = {
        "dr.surface": "shell-app",
        "dr.app_name": _DR_APP_NAME,
        "dr.agent_v2_id": _DR_AGENT_V2_ID,
        "dr.agent_name": _DR_AGENT_NAME,
        "dr.revision_id": _DR_REVISION_ID,
        "dr.workflow_id": workflow_id,
        "dr.workflow_name": workflow_name,
        "dr.query_preview": (query or "")[:200],
    }
    try:
        for key, value in tags.items():
            if not value:
                continue
            mlflow.set_trace_tag(key, str(value)[:512])
    except Exception as exc:  # pragma: no cover - defensive
        logger.debug("SHELL_APP_PROVENANCE_TAG_FAILED exc=%s", exc)


# ── App + workflow definition (loaded once) ─────────────────────────────

app = FastAPI(title="Deep Research Shell App")

_STATIC_DIR = Path(__file__).resolve().parent / "static"
app.mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static")

_AGENT_YAML = Path(__file__).resolve().parent / "agent.yaml"
_DEFINITION_DICT: dict[str, Any] = yaml.safe_load(_AGENT_YAML.read_text("utf-8"))
_DEFINITION = load_workflow_from_dict(_DEFINITION_DICT)

# ── Surface (structured-output dashboard) ────────────────────────────────
# The agent's declarative surface (input form + Table/MetricGrid/KeyFindings/
# Chart output slots) travels in the raw definition. When it declares output
# slots we (1) inject the schema contract into research/synthesis prompts so
# evidence targets every slot (Part A), and (2) after each run generate the
# structured-output envelope the React dashboard renders — the SAME envelope
# shape the main app persists (``verification_data["structured_output"]``).
_SURFACE: dict[str, Any] | None = (
    _DEFINITION_DICT.get("surface")
    if isinstance(_DEFINITION_DICT.get("surface"), dict)
    else None
)
_RESOLVED_BINDING = (
    resolve_binding_for_run(collect_output_slots(_SURFACE), None)
    if _SURFACE is not None
    else None
)
if _RESOLVED_BINDING is not None and _RESOLVED_BINDING.slots:
    _c_synth, _c_research = inject_structured_output_contract(
        _DEFINITION, _RESOLVED_BINDING.slots
    )
    logger.info(
        "SHELL_APP_SURFACE_CONTRACT_INJECTED binding=%s slots=%d "
        "synthesizers=%d researchers=%d",
        _RESOLVED_BINDING.action,
        len(_RESOLVED_BINDING.slots),
        _c_synth,
        _c_research,
    )

# LLM client + base workspace client are shared across requests (lifecycle
# is process-scoped). The base workspace client is the app SP; we derive its
# host once so per-request OBO clients can be built without re-detecting auth.
_BRAVE_API_KEY = os.environ.get("BRAVE_API_KEY")
_llm_client = FrameworkLLMClient.from_databricks()
try:
    _SP_WORKSPACE_CLIENT: WorkspaceClient | None = WorkspaceClient()
    _SP_HOST = _SP_WORKSPACE_CLIENT.config.host
except Exception as exc:  # pragma: no cover - defensive
    logger.warning("SHELL_APP_SP_WS_CLIENT_INIT_FAILED exc=%s", exc)
    _SP_WORKSPACE_CLIENT = None
    _SP_HOST = None


def _resolve_table_warehouse_id() -> str | None:
    value = os.environ.get("TABLE_TOOLS_WAREHOUSE_ID") or os.environ.get(
        "STORAGE_WAREHOUSE_ID"
    )
    return value.strip() if value else None


def _wire_text_table_context(ctx: ToolFactoryContext) -> ToolFactoryContext:
    """Populate table-tool dependencies expected by framework factories."""
    return wire_statement_execution_text_table_context(
        ctx,
        warehouse_id=_resolve_table_warehouse_id(),
    )


# Default factory context used when no OBO token reaches the handler
# (local invocations, health probes, etc.). Production requests build a
# fresh OBO-bound context inside the request handler so vector_search /
# Genie / serving endpoints run with the caller's UC permissions.
_factory_context = ToolFactoryContext.from_defaults(
    workspace_client=_SP_WORKSPACE_CLIENT,
    brave_api_key=_BRAVE_API_KEY,
)
_wire_text_table_context(_factory_context)

# Whether this workflow declares any Databricks-bound tool (vector_search,
# Genie, table_*, compute, ...). Uses the framework's authoritative kind set
# + helper (workflow_requires_databricks / DATABRICKS_BOUND_TOOL_KINDS) so the
# shell-app and the main app stay in lockstep — no inline copy to drift. Gates
# the fail-closed OBO check in ``/api/chat``: a Databricks-bound workflow with
# no user OBO token would otherwise run every tool as the app SP and return UC
# permission errors / empty results.
_WORKFLOW_REQUIRES_DATABRICKS = workflow_requires_databricks(_DEFINITION)

# Databricks Apps runtime sets DATABRICKS_APP_NAME. Local `uv run uvicorn`
# does not. We only fail-closed on missing OBO when both: the runtime is
# Apps AND the workflow actually needs Databricks-bound tools. This keeps
# notebook-style local development working while enforcing OBO for real
# deployments that hit UC-gated resources.
_IS_DATABRICKS_APPS_RUNTIME = bool(os.environ.get("DATABRICKS_APP_NAME"))


def _build_per_request_runner(user_token: str | None) -> WorkflowRunner:
    """Build a fresh WorkflowRunner whose ToolFactoryContext is OBO-bound.

    Delegates to the framework's ``build_databricks_workflow_runner`` so the
    shell-app and the main app share ONE tool-wiring implementation. The
    user's ``x-forwarded-access-token`` is used as a static bearer token via
    ``auth_type="pat"`` (inside the framework helper), so downstream factories
    build VS / Genie / table / endpoint tools that query Databricks as the
    calling user — the only way UC-gated resources become reachable in the
    deployed shell app.

    When ``user_token`` is missing, the runner falls back to the app SP.
    The ``/api/chat`` handler refuses to call this path under the Apps
    runtime when the workflow declares Databricks-bound tools (see
    ``_IS_DATABRICKS_APPS_RUNTIME`` + ``_WORKFLOW_REQUIRES_DATABRICKS``),
    so the SP fallback only applies to local-dev and purely-web workflows.
    """
    # Delegates to the framework's shared builder so the shell-app and the
    # main app use ONE implementation: OBO when a user token is present
    # (built with auth_type="pat" inside the helper), the app SP otherwise.
    return build_databricks_workflow_runner(
        llm_client=_llm_client,
        sp_workspace_client=_SP_WORKSPACE_CLIENT,
        user_token=user_token,
        warehouse_id=_resolve_table_warehouse_id(),
        brave_api_key=_BRAVE_API_KEY,
    )


def _declared_tool_names(definition: dict[str, Any]) -> list[str]:
    """Return top-level declared tool names for safe startup diagnostics."""
    tools = definition.get("tools") or []
    if not isinstance(tools, list):
        return []
    names: list[str] = []
    for tool in tools:
        if isinstance(tool, dict):
            name = tool.get("name") or tool.get("kind")
            if isinstance(name, str):
                names.append(name)
    return names


def _source_to_dict(source: Any) -> dict[str, Any]:
    """Serialize framework source shapes without assuming one model type."""
    if isinstance(source, dict):
        return {
            "url": source.get("url"),
            "title": source.get("title"),
        }
    return {
        "url": getattr(source, "url", None),
        "title": getattr(source, "title", None),
    }


def _short_header(request: Request, name: str, max_length: int = 160) -> str:
    """Return bounded request-header text for diagnostics."""
    value = request.headers.get(name, "")
    return value[:max_length]


def _preview(value: Any, max_length: int = 200) -> str:
    """Return bounded workflow diagnostic text."""
    text = " ".join(str(value or "").split())
    if len(text) <= max_length:
        return text
    return text[: max_length - 15].rstrip() + " ...(truncated)"


def _first_planner_guidance(definition: dict[str, Any]) -> str:
    """Find the first plan-and-execute planner guidance block."""

    def _walk(node: Any) -> str:
        if not isinstance(node, dict):
            return ""
        if node.get("type") == "plan_and_execute":
            config = node.get("config")
            if isinstance(config, dict):
                guidance = config.get("planner_guidance")
                if isinstance(guidance, str) and guidance.strip():
                    return guidance
        config = node.get("config")
        if isinstance(config, dict):
            guidance = _walk(config.get("body"))
            if guidance:
                return guidance
        children = node.get("children")
        if isinstance(children, list):
            for child in children:
                guidance = _walk(child)
                if guidance:
                    return guidance
        return ""

    return _walk(definition.get("root"))


def _root_child_ids(definition: dict[str, Any]) -> list[str]:
    """Return top-level child node ids for startup diagnostics."""
    root = definition.get("root")
    if not isinstance(root, dict):
        return []
    children = root.get("children")
    if not isinstance(children, list):
        return []
    return [str(child.get("id")) for child in children if isinstance(child, dict)]


_PLANNER_GUIDANCE = _first_planner_guidance(_DEFINITION_DICT)

logger.info(
    "SHELL_APP_WORKFLOW_LOADED workflow_id=%s workflow_name=%s tools=%s "
    "output_keys=%s has_brave_api_key=%s has_search_client=%s has_workspace_client=%s "
    "has_table_registry=%s has_table_sql_executor=%s has_table_schema_cache=%s "
    "storage_warehouse_id_present=%s "
    "requires_databricks_obo=%s is_databricks_apps_runtime=%s "
    "log_level=%s template_version=%s workflow_description=%s root_children=%s "
    "planner_guidance_present=%s planner_guidance=%s",
    getattr(_DEFINITION, "id", None),
    _DEFINITION_DICT.get("name"),
    _declared_tool_names(_DEFINITION_DICT),
    list(getattr(_DEFINITION, "output_keys", []) or []),
    bool(_BRAVE_API_KEY),
    _factory_context.search_client is not None,
    _factory_context.workspace_client is not None,
    _factory_context.table_registry is not None,
    _factory_context.sql_executor is not None,
    _factory_context.schema_cache is not None,
    bool(_resolve_table_warehouse_id()),
    _WORKFLOW_REQUIRES_DATABRICKS,
    _IS_DATABRICKS_APPS_RUNTIME,
    logging.getLevelName(_LOG_LEVEL),
    _SHELL_APP_TEMPLATE_VERSION,
    _preview(_DEFINITION_DICT.get("description")),
    _root_child_ids(_DEFINITION_DICT),
    bool(_PLANNER_GUIDANCE),
    _preview(_PLANNER_GUIDANCE),
)


# ── In-flight run registry (async dispatch + resume) ─────────────────────
# A deep-research run streams for minutes, but the Databricks Apps gateway
# imposes an *absolute* wall-clock cap (~4 min, observed on AIS) on a single
# streamed HTTP response that the SSE heartbeat CANNOT defeat. If the run is
# consumed *by* the request, the gateway cut kills the whole run (the symptom:
# the browser shows "Client error: network error" mid-run).
#
# This registry decouples the run from the request: a registry-owned
# ``asyncio.Task`` drains the producer into an append-only in-memory buffer, and
# HTTP readers (the initial POST and any resume GET) stream *from* the buffer. A
# reader disconnect cancels only the reader; the producer keeps running and stays
# resumable. The frontend reconnects across connections
# (``GET /api/chat/{run_id}/events?since=N``) and resumes from the last delivered
# event id. Mirrors the main app's designer turn registry
# (``deep_research/agent_designer/turn_registry.py``).
#
# Per-process, in-memory — correct because Apps runs a single uvicorn worker
# (``entrypoint.sh`` has no ``--workers``) and a run is ephemeral. If Apps ever
# runs >1 replica or needs restart-durability, migrate to a DB-backed event log.

_RUN_TTL_SECONDS = _env_int("SHELL_APP_RUN_TTL_SECONDS", default=900, minimum=1)
_RUN_MAX_ACTIVE = _env_int("SHELL_APP_RUN_MAX_ACTIVE", default=32, minimum=1)
_RUN_PER_USER_MAX = _env_int("SHELL_APP_RUN_PER_USER_MAX", default=4, minimum=1)
_RUN_IDLE_GRACE_SECONDS = _env_int(
    "SHELL_APP_RUN_IDLE_GRACE_SECONDS", default=60, minimum=0
)

# A buffered wire frame is the same dict the SSE response yields:
# ``{"event": <type>, "data": <json-string>}``. Its sequence number is its index
# in ``events`` and is emitted as the SSE ``id:`` line so a reconnect can resume.
_WireFrame = dict[str, str]


def _utcnow() -> datetime:
    return datetime.now(UTC)


@dataclass
class _BufferedRun:
    """A single in-flight (or finished) run and its append-only event buffer.

    Created on the running event loop (never at import) so the ``asyncio``
    primitives bind to the correct loop. ``_cond`` broadcasts to waiting readers
    whenever ``events`` grows or ``status`` changes.
    """

    run_id: str
    owner: str
    events: list[_WireFrame] = field(default_factory=list)
    status: str = "running"  # running | done | error | cancelled
    created_at: datetime = field(default_factory=_utcnow)
    last_access: datetime = field(default_factory=_utcnow)
    _cond: asyncio.Condition = field(default_factory=asyncio.Condition)
    _task: asyncio.Task[None] | None = None
    _readers: int = 0
    _grace: asyncio.TimerHandle | None = None

    @property
    def is_terminal(self) -> bool:
        return self.status != "running"

    async def append(self, frame: _WireFrame) -> None:
        async with self._cond:
            self.events.append(frame)
            self._cond.notify_all()

    async def set_status(self, status: str) -> None:
        async with self._cond:
            self.status = status
            self._cond.notify_all()


class _RunRegistry:
    """Owns the producer tasks + buffers for all in-flight runs.

    ``__init__`` creates no ``asyncio`` primitives (those bind to the loop only
    when a run starts), so the module-level singleton is import-safe.
    """

    def __init__(
        self,
        *,
        ttl_seconds: float = _RUN_TTL_SECONDS,
        max_active: int = _RUN_MAX_ACTIVE,
        per_user_max: int = _RUN_PER_USER_MAX,
        idle_grace_seconds: float = _RUN_IDLE_GRACE_SECONDS,
    ) -> None:
        self._runs: dict[str, _BufferedRun] = {}
        self._ttl_seconds = ttl_seconds
        self._max_active = max_active
        self._per_user_max = per_user_max
        self._idle_grace_seconds = idle_grace_seconds

    @property
    def per_user_max(self) -> int:
        return self._per_user_max

    def active_count_for_owner(self, owner: str) -> int:
        return sum(
            1 for r in self._runs.values() if r.owner == owner and not r.is_terminal
        )

    def start(
        self, *, owner: str, run_id: str, producer: AsyncIterator[_WireFrame]
    ) -> _BufferedRun:
        """Register a run and drain ``producer`` in a registry-owned task.

        The task is owned here (not by any HTTP request), so a reader disconnect
        never cancels it. Opportunistically sweeps terminal runs first.
        """
        self.sweep()
        run = _BufferedRun(run_id=run_id, owner=owner)
        self._runs[run.run_id] = run
        run._task = asyncio.create_task(self._drain(run, producer))
        logger.info(
            "SHELL_APP_RUN_STARTED run_id=%s owner=%s active=%d",
            run.run_id,
            owner,
            len(self._runs),
        )
        return run

    def get(self, run_id: str, *, owner: str) -> _BufferedRun | None:
        """Return the run iff it exists AND is owned by ``owner`` (else None, so
        the caller answers 404 without leaking existence)."""
        run = self._runs.get(run_id)
        if run is None or run.owner != owner:
            return None
        return run

    async def _drain(
        self, run: _BufferedRun, producer: AsyncIterator[_WireFrame]
    ) -> None:
        """Pump every frame from ``producer`` into the buffer until terminal.

        The producer already converts its own failures into an ``error`` wire
        frame + ``complete``; the ``except`` here is a safety net for an uncaught
        escape, appending a sanitized ``error`` so a reconnecting client always
        sees a clean terminal.
        """
        try:
            async for frame in producer:
                await run.append(frame)
            await run.set_status("done")
            logger.info(
                "SHELL_APP_RUN_COMPLETED run_id=%s events=%d status=done",
                run.run_id,
                len(run.events),
            )
        except asyncio.CancelledError:
            run.status = "cancelled"
            logger.info(
                "SHELL_APP_RUN_RECLAIMED run_id=%s events=%d (no active reader)",
                run.run_id,
                len(run.events),
            )
            raise
        except Exception:  # noqa: BLE001 — surfaced as a sanitized terminal frame
            logger.exception("SHELL_APP_RUN_PRODUCER_FAILED run_id=%s", run.run_id)
            await run.append(
                {
                    "event": "error",
                    "data": json.dumps(
                        {
                            "type": "error",
                            "error_kind": "runtime_error",
                            "message": "The run failed. See server logs for details.",
                        }
                    ),
                }
            )
            await run.set_status("error")

    async def stream(
        self, run: _BufferedRun, *, start_seq: int
    ) -> AsyncIterator[_WireFrame]:
        """Yield buffered frames from ``start_seq`` (resumable), each tagged with
        its sequence as the SSE ``id``.

        The producer is NEVER cancelled here — a reader detach only decrements
        the refcount (which may schedule an idle-grace reclaim of a reader-less
        run). Termination is **status-based**: the shell app has no explicit
        ``done`` frame (terminals are the synthetic ``complete``/``error``), and a
        mid-stream framework ``error`` event must not end the reader early.
        Idle keepalive is handled by ``EventSourceResponse(ping=...)`` while this
        generator awaits, so no manual keepalive is emitted.
        """
        self._attach(run)
        seq = max(start_seq, 0)
        try:
            while True:
                async with run._cond:
                    # Bind ``seq`` by value — the predicate is evaluated within
                    # this iteration only, before ``seq`` advances below.
                    await run._cond.wait_for(
                        lambda current=seq: len(run.events) > current
                        or run.is_terminal
                    )
                while seq < len(run.events):
                    frame = run.events[seq]
                    yield {**frame, "id": str(seq)}
                    seq += 1
                run.last_access = _utcnow()
                if run.is_terminal and seq >= len(run.events):
                    return
        finally:
            self._detach(run)

    def _attach(self, run: _BufferedRun) -> None:
        run._readers += 1
        if run._grace is not None:
            run._grace.cancel()
            run._grace = None

    def _detach(self, run: _BufferedRun) -> None:
        run._readers = max(run._readers - 1, 0)
        if run._readers == 0 and not run.is_terminal and self._idle_grace_seconds >= 0:
            loop = asyncio.get_running_loop()
            run._grace = loop.call_later(self._idle_grace_seconds, self._reclaim, run)

    def _reclaim(self, run: _BufferedRun) -> None:
        """Cancel a still-running, reader-less run to stop orphaned token burn."""
        run._grace = None
        if run._readers == 0 and not run.is_terminal and run._task is not None:
            logger.info("SHELL_APP_RUN_RECLAIM run_id=%s (idle, no readers)", run.run_id)
            run._task.cancel()

    def sweep(self) -> int:
        """Evict terminal, reader-less runs older than the TTL; cap total runs."""
        now = _utcnow()
        evicted = 0
        for run_id in list(self._runs):
            run = self._runs[run_id]
            if (
                run.is_terminal
                and run._readers == 0
                and (now - run.last_access).total_seconds() > self._ttl_seconds
            ):
                del self._runs[run_id]
                evicted += 1
        if len(self._runs) > self._max_active:
            evictable = sorted(
                (r for r in self._runs.values() if r.is_terminal and r._readers == 0),
                key=lambda r: r.last_access,
            )
            overflow = len(self._runs) - self._max_active
            for run in evictable[:overflow]:
                del self._runs[run.run_id]
                evicted += 1
        if evicted:
            logger.info(
                "SHELL_APP_RUN_EVICTED count=%d remaining=%d",
                evicted,
                len(self._runs),
            )
        return evicted


# Module-level singleton — one per process (single uvicorn worker on Apps).
_run_registry = _RunRegistry()


def _single_error_stream(
    code: str, message: str, *, error_kind: str = "client_error"
) -> AsyncIterator[_WireFrame]:
    """A one-frame producer that emits a single ``error`` wire frame.

    Used for the pre-run rejections (missing OBO, over-cap, expired resume) that
    must surface as an SSE ``error`` event the UI already understands.
    """

    async def _gen() -> AsyncIterator[_WireFrame]:
        yield {
            "event": "error",
            "data": json.dumps(
                {
                    "type": "error",
                    "error_kind": error_kind,
                    "code": code,
                    "message": message,
                }
            ),
        }

    return _gen()


def _request_owner(request: Request) -> str:
    """Best-effort owner key for run authorization + per-user caps.

    Databricks Apps injects the caller identity; fall back to ``_anon`` in local
    dev. The unguessable ``run_id`` capability is the primary boundary; this owner
    check is defense-in-depth so one signed-in user can't resume another's run.
    """
    return (
        request.headers.get("x-forwarded-user")
        or request.headers.get("x-forwarded-email")
        or "_anon"
    )


# ── Routes ──────────────────────────────────────────────────────────────


@app.get("/", response_class=HTMLResponse)
async def index(request: Request) -> HTMLResponse:
    """Serve the static chat UI."""
    logger.info(
        "SHELL_APP_INDEX_SERVED template_version=%s user_agent=%s",
        _SHELL_APP_TEMPLATE_VERSION,
        _short_header(request, "user-agent"),
    )
    return HTMLResponse(
        (_STATIC_DIR / "index.html").read_text("utf-8"),
        headers=_NO_STORE_HEADERS,
    )


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/config")
async def config() -> dict[str, Any]:
    """Bootstrap for the React shell UI: the agent name + declarative surface.

    The surface (input form + output-slot dashboard) is rendered by the SAME
    React components the main app uses; ``surface`` is ``null`` for a plain
    research agent (the UI then shows just the query box + report).
    """
    return {
        "agent_name": _DEFINITION_DICT.get("name") or "Deep Research Agent",
        "surface": _SURFACE,
    }


# Per-owner client-error rate-limit state (in-memory; single-replica shell app).
_ERR_RATE: dict[str, list[float]] = {}
_ERR_MAX_PER_MIN = 30
_ERR_MAX_BODY = 24 * 1024  # 24 KiB


@app.post("/api/observability/client-errors")
async def client_errors(request: Request) -> dict[str, int]:
    """Log a client-side error report so a browser crash in the deployed shell UI
    lands in the app logs (mirrors the main app's
    ``POST /api/v1/observability/client-errors``). Best-effort: size-capped +
    per-owner rate-limited; never trusts client input beyond bounded logging.
    """
    raw = await request.body()
    if len(raw) > _ERR_MAX_BODY:
        raise HTTPException(status_code=413, detail="report exceeds 24 KiB")

    owner = _request_owner(request)
    now = time.time()
    times = _ERR_RATE.setdefault(owner, [])
    times[:] = [t for t in times if now - t <= 60]
    if len(times) >= _ERR_MAX_PER_MIN:
        raise HTTPException(status_code=429, detail="rate limit")
    times.append(now)

    try:
        body: dict[str, Any] = json.loads(raw or b"{}")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail="invalid JSON") from exc

    def _field(key: str, cap: int) -> str:
        val = body.get(key)
        return str(val)[:cap] if val is not None else "-"

    logger.warning(
        "client_error | kind=%s | boundary=%s | route=%s | bundle=%s | owner=%s "
        "| msg=%s | stack=%s",
        _field("kind", 48),
        _field("boundary_name", 128),
        _field("route", 512),
        _field("bundle_id", 64),
        owner,
        _field("message", 512),
        _field("stack", 4096),
    )
    return {"accepted": 1}


@app.post("/api/chat")
async def chat(request: Request) -> EventSourceResponse:
    """SSE endpoint — streams research events as they happen.

    Uses the framework's ``StreamEvent`` discriminated union (event.event_type,
    event.model_dump_json) — NO ``getattr`` / ``hasattr`` for type safety
    (Constitution principle 4).
    """
    body: dict[str, Any] = await request.json()
    query = body.get("query", "")
    # The run_id doubles as the SSE ``X-Shell-App-Request-Id`` and the resume
    # key (GET /api/chat/{run_id}/events). Full hex — an unguessable capability
    # the client uses to reconnect after a gateway connection cut.
    request_id = uuid4().hex
    owner = _request_owner(request)
    # Databricks Apps injects the caller's OAuth token here for OBO. Without
    # this, vector_search / Genie / endpoint queries run as the shell-app SP
    # and any UC-gated resource (e.g. private vector indexes) silently
    # returns empty.
    user_token = request.headers.get("x-forwarded-access-token") or None

    # Fail closed under the Databricks Apps runtime when the workflow needs
    # OBO-bound tools but the caller didn't forward a token. Without this
    # guard, the request would run against the app SP and silently return
    # "0 sources" — exactly the bug this template version fixes. Local-dev
    # callers (no DATABRICKS_APP_NAME) and purely-web workflows are
    # exempt; they continue to work without OBO.
    if (
        _IS_DATABRICKS_APPS_RUNTIME
        and _WORKFLOW_REQUIRES_DATABRICKS
        and not user_token
    ):
        logger.warning(
            "SHELL_APP_CHAT_MISSING_OBO request_id=%s workflow_name=%s "
            "is_databricks_apps_runtime=%s requires_databricks_obo=%s",
            request_id,
            _DEFINITION_DICT.get("name"),
            _IS_DATABRICKS_APPS_RUNTIME,
            _WORKFLOW_REQUIRES_DATABRICKS,
        )

        return EventSourceResponse(
            _single_error_stream(
                "missing_obo_token",
                (
                    "This workflow requires Databricks user identity "
                    "(x-forwarded-access-token) to query its data sources, but "
                    "the request did not include one. If you are running the "
                    "deployed app from a browser, sign in via the Databricks "
                    "Apps landing page; if you are calling the API directly, "
                    "forward your OBO token."
                ),
                error_kind="missing_obo",
            ),
            headers={
                **_NO_STORE_HEADERS,
                "X-Shell-App-Request-Id": request_id,
            },
        )

    # Per-owner concurrency cap: bounds buffered runs in memory and double
    # submits. Reconnects are GETs (no new run) so they don't count here.
    if _run_registry.active_count_for_owner(owner) >= _run_registry.per_user_max:
        logger.warning(
            "SHELL_APP_RUN_OVER_CAP owner=%s per_user_max=%s",
            owner,
            _run_registry.per_user_max,
        )
        return EventSourceResponse(
            _single_error_stream(
                "run_in_progress",
                (
                    "A research run is already in progress. Wait for it to "
                    "finish (or reload the page) before starting another."
                ),
                error_kind="over_capacity",
            ),
            headers={**_NO_STORE_HEADERS, "X-Shell-App-Request-Id": request_id},
        )

    runner = _build_per_request_runner(user_token)
    logger.info(
        "SHELL_APP_CHAT_START request_id=%s query_length=%s "
        "workflow_name=%s planner_guidance_present=%s "
        "obo_token_present=%s "
        "mlflow_enabled=%s sse_heartbeat_seconds=%s "
        "client_template=%s accept=%s user_agent=%s",
        request_id,
        len(str(query)),
        _DEFINITION_DICT.get("name"),
        bool(_PLANNER_GUIDANCE),
        bool(user_token),
        _MLFLOW_ENABLED,
        _SSE_HEARTBEAT_SECONDS,
        _short_header(request, "x-shell-app-template-version"),
        _short_header(request, "accept"),
        _short_header(request, "user-agent"),
    )

    async def _produce() -> AsyncIterator[_WireFrame]:
        event_count = 0
        # If enabled, wrap the run in a root MLflow span so framework spans
        # nest beneath one trace with ``dr.*`` provenance tags.
        span_cm = None
        if _MLFLOW_ENABLED:
            span_cm = mlflow.start_span(
                name=f"shell_app_chat.{_DR_APP_NAME or 'unknown'}"
            )
            try:
                span_cm.__enter__()
            except Exception as exc:  # pragma: no cover - defensive
                logger.warning(
                    "SHELL_APP_MLFLOW_SPAN_START_FAILED request_id=%s exc=%s",
                    request_id,
                    exc,
                )
                span_cm = None
        _set_dr_provenance_tags(
            query=str(query),
            workflow_id=str(getattr(_DEFINITION, "id", "") or ""),
            workflow_name=str(_DEFINITION_DICT.get("name", "") or ""),
        )
        # Only pass strict_tool_resolution to frameworks that accept it.
        # Older databricks-deep-research releases lack this kwarg; passing it
        # raises TypeError at runtime (see SHELL_APP_STREAM_KWARG_INCOMPATIBLE).
        # Production callers should opt in so factory misconfig (missing
        # index_name, dead workspace_client, etc.) raises WorkflowError
        # instead of being swallowed as a warning. The except-Exception
        # block below surfaces such errors as SSE error events for the UI.
        stream_kwargs: dict[str, Any] = {
            "workflow": _DEFINITION,
            "query": query,
        }
        if _SUPPORTS_STRICT_TOOL_RESOLUTION:
            stream_kwargs["strict_tool_resolution"] = True
        try:
            async for event in runner.stream(**stream_kwargs):
                event_count += 1
                if event_count <= 5 or event.event_type in {
                    "workflow_completed",
                    "error",
                }:
                    logger.info(
                        "SHELL_APP_STREAM_EVENT request_id=%s event_count=%s "
                        "event_type=%s node_id=%s",
                        request_id,
                        event_count,
                        event.event_type,
                        getattr(event, "node_id", None),
                    )
                # Surface tool failures at WARN. The framework's tools (VS,
                # Genie, etc.) return ToolResult(success=False) when
                # get_index discovery fails or query_index raises — without
                # this log line those failures are buried in the SSE stream
                # and the deployed surface looks the same as "0 sources
                # found", which made the original OBO bug invisible.
                if isinstance(event, ToolResultEvent) and not event.tool_success:
                    logger.warning(
                        "SHELL_APP_TOOL_FAILURE request_id=%s tool=%s "
                        "source_count=%s reason=%s",
                        request_id,
                        event.tool_name,
                        event.source_count,
                        (event.tool_error or "")[:300],
                    )
                yield {
                    "event": event.event_type,
                    "data": event.model_dump_json(),
                }
            result = runner.last_result
            sources = [
                _source_to_dict(s)
                for s in (result.sources[:10] if result else [])
            ]
            logger.info(
                "SHELL_APP_CHAT_COMPLETE request_id=%s event_count=%s "
                "output_length=%s source_count=%s",
                request_id,
                event_count,
                len(result.output if result else ""),
                len(sources),
            )
            # Structured-output dashboard: emit a pending stub (skeletons) then
            # generate the envelope over the run's evidence and emit the filled
            # one BEFORE ``complete`` (the terminal frame). Best-effort — a
            # generation failure leaves the report intact, dashboard empty.
            if _RESOLVED_BINDING is not None and _RESOLVED_BINDING.slots:
                slot_names = list(_RESOLVED_BINDING.slots)
                yield {
                    "event": "structured_output",
                    "data": json.dumps(
                        build_pending_envelope(
                            binding=_RESOLVED_BINDING.action,
                            agent_id=_DR_AGENT_V2_ID or None,
                            surface_etag=None,
                            slot_names=slot_names,
                        )
                    ),
                }
                try:
                    envelope = await build_structured_envelope(
                        binding=_RESOLVED_BINDING.action,
                        agent_id=_DR_AGENT_V2_ID or None,
                        surface_etag=None,
                        slots=_RESOLVED_BINDING.slots,
                        report=result.output if result else "",
                        claims=[],
                        sources=list(result.sources) if result else [],
                        llm=_llm_client,
                    )
                    yield {
                        "event": "structured_output",
                        "data": json.dumps(envelope),
                    }
                    logger.info(
                        "SHELL_APP_STRUCTURED_OUTPUT request_id=%s slots=%s",
                        request_id,
                        len(slot_names),
                    )
                except Exception as exc:  # noqa: BLE001 — dashboard best-effort
                    logger.warning(
                        "SHELL_APP_STRUCTURED_OUTPUT_FAILED request_id=%s exc=%s",
                        request_id,
                        str(exc)[:300],
                    )
            yield {
                "event": "complete",
                "data": json.dumps(
                    {
                        "type": "complete",
                        "output": result.output if result else "",
                        "sources": sources,
                    }
                ),
            }
        except asyncio.CancelledError:
            logger.warning(
                "SHELL_APP_CHAT_CLIENT_DISCONNECTED request_id=%s event_count=%s",
                request_id,
                event_count,
            )
            raise
        except Exception as exc:  # noqa: BLE001 — surface to UI as 'error' event
            # Classify the exception so the UI can render an actionable
            # next-step instead of a raw Python error string. Phase 3 M4.
            error_kind = _classify_shell_app_exception(exc)
            logger.exception(
                "SHELL_APP_CHAT_ERROR request_id=%s event_count=%s "
                "exc_class=%s error_kind=%s",
                request_id,
                event_count,
                type(exc).__name__,
                error_kind,
            )
            yield {
                "event": "error",
                "data": json.dumps(
                    {
                        "type": "error",
                        "error_kind": error_kind,
                        "message": str(exc),
                        "exc_class": type(exc).__name__,
                    }
                ),
            }
        finally:
            # Close the root MLflow span. Mirrors __exit__ semantics so the
            # span is flushed even on error paths. Failures are swallowed —
            # we never want tracing cleanup to mask the real error.
            if span_cm is not None:
                trace_close_started = time.monotonic()
                try:
                    span_cm.__exit__(None, None, None)
                except Exception as exc:  # pragma: no cover - defensive
                    logger.warning(
                        "SHELL_APP_MLFLOW_SPAN_CLOSE_FAILED request_id=%s "
                        "elapsed_ms=%s exc=%s",
                        request_id,
                        int((time.monotonic() - trace_close_started) * 1000),
                        exc,
                    )
                else:
                    logger.info(
                        "SHELL_APP_MLFLOW_SPAN_CLOSED request_id=%s elapsed_ms=%s",
                        request_id,
                        int((time.monotonic() - trace_close_started) * 1000),
                    )
            logger.info(
                "SHELL_APP_CHAT_STREAM_CLOSED request_id=%s event_count=%s "
                "mlflow_enabled=%s",
                request_id,
                event_count,
                _MLFLOW_ENABLED,
            )

    # Decouple the run from this request: a registry-owned task drains _produce
    # into an append-only buffer that survives the gateway's absolute connection
    # cap, so the client can reconnect (GET …/events?since=N) and resume.
    run = _run_registry.start(owner=owner, run_id=request_id, producer=_produce())
    return EventSourceResponse(
        _run_registry.stream(run, start_seq=0),
        headers={**_NO_STORE_HEADERS, "X-Shell-App-Request-Id": run.run_id},
        ping=_SSE_HEARTBEAT_SECONDS,
    )


@app.get("/api/chat/{run_id}/events")
async def chat_events(
    run_id: str, request: Request, since: int = Query(0, ge=0)
) -> EventSourceResponse:
    """Resume an in-flight (or finished) run from sequence ``since``.

    The frontend calls this when the streamed POST is severed by the gateway's
    absolute connection cap. It replays ``events[since:]`` — including a terminal
    ``complete``/``error`` produced while disconnected — and keeps the heartbeat
    so this connection also survives idle gaps until the next cap. An unknown,
    expired, or foreign-owned id returns a single ``expired`` error frame (no
    existence leak), which the UI turns into a re-run prompt.
    """
    owner = _request_owner(request)
    run = _run_registry.get(run_id, owner=owner)
    if run is None:
        logger.info("SHELL_APP_RUN_RESUME_MISS run_id=%s since=%s", run_id, since)
        return EventSourceResponse(
            _single_error_stream(
                "run_expired",
                "This run was not found or has expired. Please resend your query.",
                error_kind="expired",
            ),
            headers={**_NO_STORE_HEADERS, "X-Shell-App-Request-Id": run_id},
        )
    logger.info(
        "SHELL_APP_RUN_RESUME run_id=%s owner=%s since=%s", run_id, owner, since
    )
    return EventSourceResponse(
        _run_registry.stream(run, start_seq=since),
        headers={**_NO_STORE_HEADERS, "X-Shell-App-Request-Id": run_id},
        ping=_SSE_HEARTBEAT_SECONDS,
    )
