"""Shell-app FastAPI entry point.

Generated by ``ShellAppExporter``. Renders a minimal chat UI bound to one
``WorkflowDefinition`` AST embedded at deploy time. The framework is
pip-installed via the Git tag pin in ``pyproject.toml`` (no PyPI yet).

Plan reference: agent-designer-deployment.md Section E.5.
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any
from uuid import uuid4

import mlflow
import yaml
from databricks_deep_research import FrameworkLLMClient, ToolFactoryContext, WorkflowRunner
from databricks_deep_research.tracing import setup_mlflow_tracing
from databricks_deep_research.workflow.loader import load_workflow_from_dict
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from sse_starlette.sse import EventSourceResponse

_LOG_LEVEL_NAME = os.environ.get("LOG_LEVEL", "INFO").upper()
_LOG_LEVEL = getattr(logging, _LOG_LEVEL_NAME, logging.INFO)
logging.basicConfig(
    level=_LOG_LEVEL,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logging.getLogger().setLevel(_LOG_LEVEL)
logger = logging.getLogger(__name__)
logger.setLevel(_LOG_LEVEL)
_SHELL_APP_TEMPLATE_VERSION = "2026-05-17.1"
_NO_STORE_HEADERS = {
    "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
    "Pragma": "no-cache",
    "Expires": "0",
    "X-Shell-App-Template-Version": _SHELL_APP_TEMPLATE_VERSION,
}


# ── MLflow tracing setup ─────────────────────────────────────────────────
# All deployed shell-apps write to the shared experiment so every trace
# (designer-chat, main-chat, shell-app) lives in one queryable surface.
# Provenance is sourced from the DR_* env vars Jinja-interpolated by the
# ShellAppExporter at deploy time.

_MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "databricks")
_MLFLOW_EXPERIMENT_NAME = os.environ.get(
    "MLFLOW_EXPERIMENT_NAME", "/Shared/deep-research-agent-experiments"
)
_DR_APP_NAME = os.environ.get("DR_APP_NAME", "")
_DR_AGENT_V2_ID = os.environ.get("DR_AGENT_V2_ID", "")
_DR_AGENT_NAME = os.environ.get("DR_AGENT_NAME", "")
_DR_REVISION_ID = os.environ.get("DR_REVISION_ID", "")

try:
    setup_mlflow_tracing(
        tracking_uri=_MLFLOW_TRACKING_URI,
        experiment_name=_MLFLOW_EXPERIMENT_NAME,
    )
    logger.info(
        "SHELL_APP_MLFLOW_TRACING_INITIALIZED tracking_uri=%s experiment=%s "
        "app_name=%s agent_v2_id=%s revision_id=%s",
        _MLFLOW_TRACKING_URI, _MLFLOW_EXPERIMENT_NAME,
        _DR_APP_NAME, _DR_AGENT_V2_ID, _DR_REVISION_ID,
    )
except Exception as exc:  # pragma: no cover - tracing must never fail boot
    logger.warning("SHELL_APP_MLFLOW_TRACING_INIT_FAILED exc=%s", exc)


def _set_dr_provenance_tags(query: str, workflow_id: str, workflow_name: str) -> None:
    """Tag the current MLflow trace with dr.* provenance fields.

    Mirrors ``deep_research.core.trace_provenance.set_trace_provenance`` —
    duplicated here because the shell-app template is shipped without a
    dependency on the main app's package. Safe to call when mlflow has no
    active trace; failures are swallowed (tracing is best-effort).
    """
    tags = {
        "dr.surface": "shell-app",
        "dr.app_name": _DR_APP_NAME,
        "dr.agent_v2_id": _DR_AGENT_V2_ID,
        "dr.agent_name": _DR_AGENT_NAME,
        "dr.revision_id": _DR_REVISION_ID,
        "dr.workflow_id": workflow_id,
        "dr.workflow_name": workflow_name,
        "dr.query_preview": (query or "")[:200],
    }
    try:
        for key, value in tags.items():
            if not value:
                continue
            mlflow.set_trace_tag(key, str(value)[:512])
    except Exception as exc:  # pragma: no cover - defensive
        logger.debug("SHELL_APP_PROVENANCE_TAG_FAILED exc=%s", exc)


# ── App + workflow definition (loaded once) ─────────────────────────────

app = FastAPI(title="Deep Research Shell App")

_STATIC_DIR = Path(__file__).resolve().parent / "static"
app.mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static")

_AGENT_YAML = Path(__file__).resolve().parent / "agent.yaml"
_DEFINITION_DICT: dict[str, Any] = yaml.safe_load(_AGENT_YAML.read_text("utf-8"))
_DEFINITION = load_workflow_from_dict(_DEFINITION_DICT)

# Runner is bound to workspace creds via FrameworkLLMClient.from_databricks().
# Construct WorkflowRunner directly so deployed shell apps also work with
# framework refs whose WorkflowRunner.from_databricks() predates factory_context.
_BRAVE_API_KEY = os.environ.get("BRAVE_API_KEY")
_factory_context = ToolFactoryContext.from_defaults(brave_api_key=_BRAVE_API_KEY)
_llm_client = FrameworkLLMClient.from_databricks()
_runner = WorkflowRunner(llm_client=_llm_client, factory_context=_factory_context)


def _declared_tool_names(definition: dict[str, Any]) -> list[str]:
    """Return top-level declared tool names for safe startup diagnostics."""
    tools = definition.get("tools") or []
    if not isinstance(tools, list):
        return []
    names: list[str] = []
    for tool in tools:
        if isinstance(tool, dict):
            name = tool.get("name") or tool.get("kind")
            if isinstance(name, str):
                names.append(name)
    return names


def _source_to_dict(source: Any) -> dict[str, Any]:
    """Serialize framework source shapes without assuming one model type."""
    if isinstance(source, dict):
        return {
            "url": source.get("url"),
            "title": source.get("title"),
        }
    return {
        "url": getattr(source, "url", None),
        "title": getattr(source, "title", None),
    }


def _short_header(request: Request, name: str, max_length: int = 160) -> str:
    """Return bounded request-header text for diagnostics."""
    value = request.headers.get(name, "")
    return value[:max_length]


def _preview(value: Any, max_length: int = 200) -> str:
    """Return bounded workflow diagnostic text."""
    text = " ".join(str(value or "").split())
    if len(text) <= max_length:
        return text
    return text[: max_length - 15].rstrip() + " ...(truncated)"


def _first_planner_guidance(definition: dict[str, Any]) -> str:
    """Find the first plan-and-execute planner guidance block."""

    def _walk(node: Any) -> str:
        if not isinstance(node, dict):
            return ""
        if node.get("type") == "plan_and_execute":
            config = node.get("config")
            if isinstance(config, dict):
                guidance = config.get("planner_guidance")
                if isinstance(guidance, str) and guidance.strip():
                    return guidance
        config = node.get("config")
        if isinstance(config, dict):
            guidance = _walk(config.get("body"))
            if guidance:
                return guidance
        children = node.get("children")
        if isinstance(children, list):
            for child in children:
                guidance = _walk(child)
                if guidance:
                    return guidance
        return ""

    return _walk(definition.get("root"))


def _root_child_ids(definition: dict[str, Any]) -> list[str]:
    """Return top-level child node ids for startup diagnostics."""
    root = definition.get("root")
    if not isinstance(root, dict):
        return []
    children = root.get("children")
    if not isinstance(children, list):
        return []
    return [str(child.get("id")) for child in children if isinstance(child, dict)]


_PLANNER_GUIDANCE = _first_planner_guidance(_DEFINITION_DICT)

logger.info(
    "SHELL_APP_WORKFLOW_LOADED workflow_id=%s workflow_name=%s tools=%s "
    "output_keys=%s has_brave_api_key=%s has_search_client=%s has_workspace_client=%s "
    "log_level=%s template_version=%s workflow_description=%s root_children=%s "
    "planner_guidance_present=%s planner_guidance=%s",
    getattr(_DEFINITION, "id", None),
    _DEFINITION_DICT.get("name"),
    _declared_tool_names(_DEFINITION_DICT),
    list(getattr(_DEFINITION, "output_keys", []) or []),
    bool(_BRAVE_API_KEY),
    _factory_context.search_client is not None,
    _factory_context.workspace_client is not None,
    logging.getLevelName(_LOG_LEVEL),
    _SHELL_APP_TEMPLATE_VERSION,
    _preview(_DEFINITION_DICT.get("description")),
    _root_child_ids(_DEFINITION_DICT),
    bool(_PLANNER_GUIDANCE),
    _preview(_PLANNER_GUIDANCE),
)


# ── Routes ──────────────────────────────────────────────────────────────


@app.get("/", response_class=HTMLResponse)
async def index(request: Request) -> HTMLResponse:
    """Serve the static chat UI."""
    logger.info(
        "SHELL_APP_INDEX_SERVED template_version=%s user_agent=%s",
        _SHELL_APP_TEMPLATE_VERSION,
        _short_header(request, "user-agent"),
    )
    return HTMLResponse(
        (_STATIC_DIR / "index.html").read_text("utf-8"),
        headers=_NO_STORE_HEADERS,
    )


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/api/chat")
async def chat(request: Request) -> EventSourceResponse:
    """SSE endpoint — streams research events as they happen.

    Uses the framework's ``StreamEvent`` discriminated union (event.event_type,
    event.model_dump_json) — NO ``getattr`` / ``hasattr`` for type safety
    (Constitution principle 4).
    """
    body: dict[str, Any] = await request.json()
    query = body.get("query", "")
    request_id = uuid4().hex[:12]
    logger.info(
        "SHELL_APP_CHAT_START request_id=%s query_length=%s "
        "workflow_name=%s planner_guidance_present=%s "
        "client_template=%s accept=%s user_agent=%s",
        request_id,
        len(str(query)),
        _DEFINITION_DICT.get("name"),
        bool(_PLANNER_GUIDANCE),
        _short_header(request, "x-shell-app-template-version"),
        _short_header(request, "accept"),
        _short_header(request, "user-agent"),
    )

    async def event_generator():
        event_count = 0
        # Wrap the entire run in a root MLflow span so every framework span
        # (nodes, ReAct loops, tool calls) nests beneath one trace with our
        # ``dr.*`` provenance tags. The span name embeds the app name so the
        # MLflow UI's trace list shows "which deployed app" at a glance.
        span_cm = mlflow.start_span(
            name=f"shell_app_chat.{_DR_APP_NAME or 'unknown'}"
        )
        try:
            span_cm.__enter__()
        except Exception:  # pragma: no cover - defensive
            span_cm = None
        _set_dr_provenance_tags(
            query=str(query),
            workflow_id=str(getattr(_DEFINITION, "id", "") or ""),
            workflow_name=str(_DEFINITION_DICT.get("name", "") or ""),
        )
        try:
            async for event in _runner.stream(workflow=_DEFINITION, query=query):
                event_count += 1
                if event_count <= 5 or event.event_type in {
                    "workflow_completed",
                    "error",
                }:
                    logger.info(
                        "SHELL_APP_STREAM_EVENT request_id=%s event_count=%s "
                        "event_type=%s node_id=%s",
                        request_id,
                        event_count,
                        event.event_type,
                        getattr(event, "node_id", None),
                    )
                yield {
                    "event": event.event_type,
                    "data": event.model_dump_json(),
                }
            result = _runner.last_result
            sources = [_source_to_dict(s) for s in (result.sources[:10] if result else [])]
            logger.info(
                "SHELL_APP_CHAT_COMPLETE request_id=%s event_count=%s "
                "output_length=%s source_count=%s",
                request_id,
                event_count,
                len(result.output if result else ""),
                len(sources),
            )
            yield {
                "event": "complete",
                "data": json.dumps(
                    {
                        "type": "complete",
                        "output": result.output if result else "",
                        "sources": sources,
                    }
                ),
            }
        except Exception as exc:  # noqa: BLE001 — surface to UI as 'error' event
            logger.exception(
                "SHELL_APP_CHAT_ERROR request_id=%s event_count=%s exc_class=%s",
                request_id,
                event_count,
                type(exc).__name__,
            )
            yield {
                "event": "error",
                "data": json.dumps({"type": "error", "message": str(exc)}),
            }
        finally:
            # Close the root MLflow span. Mirrors __exit__ semantics so the
            # span is flushed even on error paths. Failures are swallowed —
            # we never want tracing cleanup to mask the real error.
            if span_cm is not None:
                try:
                    span_cm.__exit__(None, None, None)
                except Exception:  # pragma: no cover - defensive
                    pass

    return EventSourceResponse(
        event_generator(),
        headers={**_NO_STORE_HEADERS, "X-Shell-App-Request-Id": request_id},
    )
