"""Shell-app FastAPI entry point.

Generated by ``ShellAppExporter``. Renders a minimal chat UI bound to one
``WorkflowDefinition`` AST embedded at deploy time. The framework is
pip-installed via the Git tag pin in ``pyproject.toml`` (no PyPI yet).

Plan reference: agent-designer-deployment.md Section E.5.
"""
from __future__ import annotations

import asyncio
import inspect
import json
import logging
import os
import time
from pathlib import Path
from typing import Any
from uuid import uuid4

import mlflow
import yaml
from databricks.sdk import WorkspaceClient
from databricks_deep_research import (
    FrameworkLLMClient,
    ToolFactoryContext,
    WorkflowRunner,
    build_databricks_workflow_runner,
    workflow_requires_databricks,
)
from databricks_deep_research.events.types import ToolResultEvent
from databricks_deep_research.tools.builtins.text_table import (
    wire_statement_execution_text_table_context,
)
from databricks_deep_research.tracing import setup_mlflow_tracing
from databricks_deep_research.workflow.loader import load_workflow_from_dict
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from sse_starlette.sse import EventSourceResponse

# Feature-detect optional kwargs on WorkflowRunner.stream so this template
# remains forward/back-compatible with frameworks that don't yet expose them.
# Older databricks-deep-research releases did not accept `strict_tool_resolution`;
# passing it unconditionally would raise `TypeError` at runtime.
try:
    _STREAM_PARAMS: set[str] = set(inspect.signature(WorkflowRunner.stream).parameters)
except (TypeError, ValueError):  # pragma: no cover - defensive
    _STREAM_PARAMS = set()
_SUPPORTS_STRICT_TOOL_RESOLUTION: bool = "strict_tool_resolution" in _STREAM_PARAMS


def _classify_traceback_modules(exc: BaseException) -> list[str]:
    """Return module names appearing in the exception's traceback frames.

    Used by :func:`_classify_shell_app_exception` to detect ``TypeError`` /
    ``AttributeError`` that originated inside the framework call chain
    (rather than user code). Defensive: returns an empty list on any
    introspection failure so classifier never raises.
    """
    try:
        tb = exc.__traceback__
        modules: list[str] = []
        while tb is not None:
            frame_module = tb.tb_frame.f_globals.get("__name__", "")
            if isinstance(frame_module, str):
                modules.append(frame_module)
            tb = tb.tb_next
        return modules
    except Exception:  # pragma: no cover - defensive
        return []


def _classify_shell_app_exception(exc: BaseException) -> str:
    """Bucket runtime exceptions so the UI can render actionable next-steps.

    Categories (Phase 3 M4):

    * ``workflow_error`` — framework refused to start or aborted the
      workflow (missing tools under strict mode, schema violations, etc.).
      User action: redesign or re-deploy the agent with corrected config.
    * ``framework_skew`` — call into framework code failed with a
      ``TypeError`` / ``AttributeError`` because the installed framework
      version doesn't match the template's expected API surface. User
      action: redeploy with an updated ``framework_git_tag``.
    * ``runtime_error`` — anything else (network, LLM, generic Python).
      User action: retry or contact support.

    The classifier is intentionally narrow: only catches well-known
    framework-side exception types. Anything we don't recognize stays as
    ``runtime_error`` so the user gets the raw message + class name.
    """
    if type(exc).__name__ == "WorkflowError":
        return "workflow_error"
    module = getattr(type(exc), "__module__", "") or ""
    if isinstance(exc, (TypeError, AttributeError)) and (
        "databricks_deep_research" in module
        or "databricks_deep_research" in "".join(_classify_traceback_modules(exc))
    ):
        return "framework_skew"
    return "runtime_error"

_LOG_LEVEL_NAME = os.environ.get("LOG_LEVEL", "INFO").upper()
_LOG_LEVEL = getattr(logging, _LOG_LEVEL_NAME, logging.INFO)
logging.basicConfig(
    level=_LOG_LEVEL,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logging.getLogger().setLevel(_LOG_LEVEL)
logger = logging.getLogger(__name__)
logger.setLevel(_LOG_LEVEL)
_SHELL_APP_TEMPLATE_VERSION = "2026-05-28.1"
_NO_STORE_HEADERS = {
    "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
    "Pragma": "no-cache",
    "Expires": "0",
    "X-Shell-App-Template-Version": _SHELL_APP_TEMPLATE_VERSION,
}


def _env_flag(name: str, *, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, *, default: int, minimum: int) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        value = int(raw)
    except ValueError:
        logger.warning(
            "SHELL_APP_INVALID_INT_ENV name=%s value=%r default=%s",
            name,
            raw,
            default,
        )
        return default
    if value < minimum:
        logger.warning(
            "SHELL_APP_INVALID_INT_ENV name=%s value=%s minimum=%s default=%s",
            name,
            value,
            minimum,
            default,
        )
        return default
    return value


# ── MLflow tracing setup ─────────────────────────────────────────────────
# Shell-app MLflow tracing is opt-in because trace artifact export can block
# long-lived SSE streams when Databricks storage is unreachable from the app.
# When enabled, provenance is sourced from the DR_* env vars Jinja-interpolated
# by the ShellAppExporter at deploy time.

_MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI", "databricks")
_MLFLOW_EXPERIMENT_NAME = os.environ.get(
    "MLFLOW_EXPERIMENT_NAME", "/Shared/deep-research-agent-experiments"
)
_DR_APP_NAME = os.environ.get("DR_APP_NAME", "")
_DR_AGENT_V2_ID = os.environ.get("DR_AGENT_V2_ID", "")
_DR_AGENT_NAME = os.environ.get("DR_AGENT_NAME", "")
_DR_REVISION_ID = os.environ.get("DR_REVISION_ID", "")
_MLFLOW_ENABLED = _env_flag("MLFLOW_ENABLED", default=False)
_SSE_HEARTBEAT_SECONDS = _env_int(
    "SHELL_APP_SSE_HEARTBEAT_SECONDS",
    default=15,
    minimum=5,
)

if _MLFLOW_ENABLED:
    try:
        setup_mlflow_tracing(
            tracking_uri=_MLFLOW_TRACKING_URI,
            experiment_name=_MLFLOW_EXPERIMENT_NAME,
        )
        logger.info(
            "SHELL_APP_MLFLOW_TRACING_INITIALIZED tracking_uri=%s experiment=%s "
            "app_name=%s agent_v2_id=%s revision_id=%s",
            _MLFLOW_TRACKING_URI, _MLFLOW_EXPERIMENT_NAME,
            _DR_APP_NAME, _DR_AGENT_V2_ID, _DR_REVISION_ID,
        )
    except Exception as exc:  # pragma: no cover - tracing must never fail boot
        logger.warning("SHELL_APP_MLFLOW_TRACING_INIT_FAILED exc=%s", exc)
else:
    logger.info(
        "SHELL_APP_MLFLOW_TRACING_DISABLED mlflow_enabled_env=%r",
        os.environ.get("MLFLOW_ENABLED"),
    )


def _set_dr_provenance_tags(query: str, workflow_id: str, workflow_name: str) -> None:
    """Tag the current MLflow trace with dr.* provenance fields.

    Mirrors ``deep_research.core.trace_provenance.set_trace_provenance`` —
    duplicated here because the shell-app template is shipped without a
    dependency on the main app's package. Safe to call when mlflow has no
    active trace; failures are swallowed (tracing is best-effort).
    """
    if not _MLFLOW_ENABLED:
        return
    tags = {
        "dr.surface": "shell-app",
        "dr.app_name": _DR_APP_NAME,
        "dr.agent_v2_id": _DR_AGENT_V2_ID,
        "dr.agent_name": _DR_AGENT_NAME,
        "dr.revision_id": _DR_REVISION_ID,
        "dr.workflow_id": workflow_id,
        "dr.workflow_name": workflow_name,
        "dr.query_preview": (query or "")[:200],
    }
    try:
        for key, value in tags.items():
            if not value:
                continue
            mlflow.set_trace_tag(key, str(value)[:512])
    except Exception as exc:  # pragma: no cover - defensive
        logger.debug("SHELL_APP_PROVENANCE_TAG_FAILED exc=%s", exc)


# ── App + workflow definition (loaded once) ─────────────────────────────

app = FastAPI(title="Deep Research Shell App")

_STATIC_DIR = Path(__file__).resolve().parent / "static"
app.mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static")

_AGENT_YAML = Path(__file__).resolve().parent / "agent.yaml"
_DEFINITION_DICT: dict[str, Any] = yaml.safe_load(_AGENT_YAML.read_text("utf-8"))
_DEFINITION = load_workflow_from_dict(_DEFINITION_DICT)

# LLM client + base workspace client are shared across requests (lifecycle
# is process-scoped). The base workspace client is the app SP; we derive its
# host once so per-request OBO clients can be built without re-detecting auth.
_BRAVE_API_KEY = os.environ.get("BRAVE_API_KEY")
_llm_client = FrameworkLLMClient.from_databricks()
try:
    _SP_WORKSPACE_CLIENT: WorkspaceClient | None = WorkspaceClient()
    _SP_HOST = _SP_WORKSPACE_CLIENT.config.host
except Exception as exc:  # pragma: no cover - defensive
    logger.warning("SHELL_APP_SP_WS_CLIENT_INIT_FAILED exc=%s", exc)
    _SP_WORKSPACE_CLIENT = None
    _SP_HOST = None


def _resolve_table_warehouse_id() -> str | None:
    value = os.environ.get("TABLE_TOOLS_WAREHOUSE_ID") or os.environ.get(
        "STORAGE_WAREHOUSE_ID"
    )
    return value.strip() if value else None


def _wire_text_table_context(ctx: ToolFactoryContext) -> ToolFactoryContext:
    """Populate table-tool dependencies expected by framework factories."""
    return wire_statement_execution_text_table_context(
        ctx,
        warehouse_id=_resolve_table_warehouse_id(),
    )


# Default factory context used when no OBO token reaches the handler
# (local invocations, health probes, etc.). Production requests build a
# fresh OBO-bound context inside the request handler so vector_search /
# Genie / serving endpoints run with the caller's UC permissions.
_factory_context = ToolFactoryContext.from_defaults(
    workspace_client=_SP_WORKSPACE_CLIENT,
    brave_api_key=_BRAVE_API_KEY,
)
_wire_text_table_context(_factory_context)

# Whether this workflow declares any Databricks-bound tool (vector_search,
# Genie, table_*, compute, ...). Uses the framework's authoritative kind set
# + helper (workflow_requires_databricks / DATABRICKS_BOUND_TOOL_KINDS) so the
# shell-app and the main app stay in lockstep — no inline copy to drift. Gates
# the fail-closed OBO check in ``/api/chat``: a Databricks-bound workflow with
# no user OBO token would otherwise run every tool as the app SP and return UC
# permission errors / empty results.
_WORKFLOW_REQUIRES_DATABRICKS = workflow_requires_databricks(_DEFINITION)

# Databricks Apps runtime sets DATABRICKS_APP_NAME. Local `uv run uvicorn`
# does not. We only fail-closed on missing OBO when both: the runtime is
# Apps AND the workflow actually needs Databricks-bound tools. This keeps
# notebook-style local development working while enforcing OBO for real
# deployments that hit UC-gated resources.
_IS_DATABRICKS_APPS_RUNTIME = bool(os.environ.get("DATABRICKS_APP_NAME"))


def _build_per_request_runner(user_token: str | None) -> WorkflowRunner:
    """Build a fresh WorkflowRunner whose ToolFactoryContext is OBO-bound.

    Delegates to the framework's ``build_databricks_workflow_runner`` so the
    shell-app and the main app share ONE tool-wiring implementation. The
    user's ``x-forwarded-access-token`` is used as a static bearer token via
    ``auth_type="pat"`` (inside the framework helper), so downstream factories
    build VS / Genie / table / endpoint tools that query Databricks as the
    calling user — the only way UC-gated resources become reachable in the
    deployed shell app.

    When ``user_token`` is missing, the runner falls back to the app SP.
    The ``/api/chat`` handler refuses to call this path under the Apps
    runtime when the workflow declares Databricks-bound tools (see
    ``_IS_DATABRICKS_APPS_RUNTIME`` + ``_WORKFLOW_REQUIRES_DATABRICKS``),
    so the SP fallback only applies to local-dev and purely-web workflows.
    """
    # Delegates to the framework's shared builder so the shell-app and the
    # main app use ONE implementation: OBO when a user token is present
    # (built with auth_type="pat" inside the helper), the app SP otherwise.
    return build_databricks_workflow_runner(
        llm_client=_llm_client,
        sp_workspace_client=_SP_WORKSPACE_CLIENT,
        user_token=user_token,
        warehouse_id=_resolve_table_warehouse_id(),
        brave_api_key=_BRAVE_API_KEY,
    )


def _declared_tool_names(definition: dict[str, Any]) -> list[str]:
    """Return top-level declared tool names for safe startup diagnostics."""
    tools = definition.get("tools") or []
    if not isinstance(tools, list):
        return []
    names: list[str] = []
    for tool in tools:
        if isinstance(tool, dict):
            name = tool.get("name") or tool.get("kind")
            if isinstance(name, str):
                names.append(name)
    return names


def _source_to_dict(source: Any) -> dict[str, Any]:
    """Serialize framework source shapes without assuming one model type."""
    if isinstance(source, dict):
        return {
            "url": source.get("url"),
            "title": source.get("title"),
        }
    return {
        "url": getattr(source, "url", None),
        "title": getattr(source, "title", None),
    }


def _short_header(request: Request, name: str, max_length: int = 160) -> str:
    """Return bounded request-header text for diagnostics."""
    value = request.headers.get(name, "")
    return value[:max_length]


def _preview(value: Any, max_length: int = 200) -> str:
    """Return bounded workflow diagnostic text."""
    text = " ".join(str(value or "").split())
    if len(text) <= max_length:
        return text
    return text[: max_length - 15].rstrip() + " ...(truncated)"


def _first_planner_guidance(definition: dict[str, Any]) -> str:
    """Find the first plan-and-execute planner guidance block."""

    def _walk(node: Any) -> str:
        if not isinstance(node, dict):
            return ""
        if node.get("type") == "plan_and_execute":
            config = node.get("config")
            if isinstance(config, dict):
                guidance = config.get("planner_guidance")
                if isinstance(guidance, str) and guidance.strip():
                    return guidance
        config = node.get("config")
        if isinstance(config, dict):
            guidance = _walk(config.get("body"))
            if guidance:
                return guidance
        children = node.get("children")
        if isinstance(children, list):
            for child in children:
                guidance = _walk(child)
                if guidance:
                    return guidance
        return ""

    return _walk(definition.get("root"))


def _root_child_ids(definition: dict[str, Any]) -> list[str]:
    """Return top-level child node ids for startup diagnostics."""
    root = definition.get("root")
    if not isinstance(root, dict):
        return []
    children = root.get("children")
    if not isinstance(children, list):
        return []
    return [str(child.get("id")) for child in children if isinstance(child, dict)]


_PLANNER_GUIDANCE = _first_planner_guidance(_DEFINITION_DICT)

logger.info(
    "SHELL_APP_WORKFLOW_LOADED workflow_id=%s workflow_name=%s tools=%s "
    "output_keys=%s has_brave_api_key=%s has_search_client=%s has_workspace_client=%s "
    "has_table_registry=%s has_table_sql_executor=%s has_table_schema_cache=%s "
    "storage_warehouse_id_present=%s "
    "requires_databricks_obo=%s is_databricks_apps_runtime=%s "
    "log_level=%s template_version=%s workflow_description=%s root_children=%s "
    "planner_guidance_present=%s planner_guidance=%s",
    getattr(_DEFINITION, "id", None),
    _DEFINITION_DICT.get("name"),
    _declared_tool_names(_DEFINITION_DICT),
    list(getattr(_DEFINITION, "output_keys", []) or []),
    bool(_BRAVE_API_KEY),
    _factory_context.search_client is not None,
    _factory_context.workspace_client is not None,
    _factory_context.table_registry is not None,
    _factory_context.sql_executor is not None,
    _factory_context.schema_cache is not None,
    bool(_resolve_table_warehouse_id()),
    _WORKFLOW_REQUIRES_DATABRICKS,
    _IS_DATABRICKS_APPS_RUNTIME,
    logging.getLevelName(_LOG_LEVEL),
    _SHELL_APP_TEMPLATE_VERSION,
    _preview(_DEFINITION_DICT.get("description")),
    _root_child_ids(_DEFINITION_DICT),
    bool(_PLANNER_GUIDANCE),
    _preview(_PLANNER_GUIDANCE),
)


# ── Routes ──────────────────────────────────────────────────────────────


@app.get("/", response_class=HTMLResponse)
async def index(request: Request) -> HTMLResponse:
    """Serve the static chat UI."""
    logger.info(
        "SHELL_APP_INDEX_SERVED template_version=%s user_agent=%s",
        _SHELL_APP_TEMPLATE_VERSION,
        _short_header(request, "user-agent"),
    )
    return HTMLResponse(
        (_STATIC_DIR / "index.html").read_text("utf-8"),
        headers=_NO_STORE_HEADERS,
    )


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/api/chat")
async def chat(request: Request) -> EventSourceResponse:
    """SSE endpoint — streams research events as they happen.

    Uses the framework's ``StreamEvent`` discriminated union (event.event_type,
    event.model_dump_json) — NO ``getattr`` / ``hasattr`` for type safety
    (Constitution principle 4).
    """
    body: dict[str, Any] = await request.json()
    query = body.get("query", "")
    request_id = uuid4().hex[:12]
    # Databricks Apps injects the caller's OAuth token here for OBO. Without
    # this, vector_search / Genie / endpoint queries run as the shell-app SP
    # and any UC-gated resource (e.g. private vector indexes) silently
    # returns empty.
    user_token = request.headers.get("x-forwarded-access-token") or None

    # Fail closed under the Databricks Apps runtime when the workflow needs
    # OBO-bound tools but the caller didn't forward a token. Without this
    # guard, the request would run against the app SP and silently return
    # "0 sources" — exactly the bug this template version fixes. Local-dev
    # callers (no DATABRICKS_APP_NAME) and purely-web workflows are
    # exempt; they continue to work without OBO.
    if (
        _IS_DATABRICKS_APPS_RUNTIME
        and _WORKFLOW_REQUIRES_DATABRICKS
        and not user_token
    ):
        logger.warning(
            "SHELL_APP_CHAT_MISSING_OBO request_id=%s workflow_name=%s "
            "is_databricks_apps_runtime=%s requires_databricks_obo=%s",
            request_id,
            _DEFINITION_DICT.get("name"),
            _IS_DATABRICKS_APPS_RUNTIME,
            _WORKFLOW_REQUIRES_DATABRICKS,
        )

        async def _missing_obo_stream():
            yield {
                "event": "error",
                "data": json.dumps(
                    {
                        "type": "error",
                        "code": "missing_obo_token",
                        "message": (
                            "This workflow requires Databricks user "
                            "identity (x-forwarded-access-token) to "
                            "query its data sources, but the request "
                            "did not include one. If you are running "
                            "the deployed app from a browser, sign in "
                            "via the Databricks Apps landing page; if "
                            "you are calling the API directly, forward "
                            "your OBO token."
                        ),
                    }
                ),
            }

        return EventSourceResponse(
            _missing_obo_stream(),
            headers={
                **_NO_STORE_HEADERS,
                "X-Shell-App-Request-Id": request_id,
            },
        )

    runner = _build_per_request_runner(user_token)
    logger.info(
        "SHELL_APP_CHAT_START request_id=%s query_length=%s "
        "workflow_name=%s planner_guidance_present=%s "
        "obo_token_present=%s "
        "mlflow_enabled=%s sse_heartbeat_seconds=%s "
        "client_template=%s accept=%s user_agent=%s",
        request_id,
        len(str(query)),
        _DEFINITION_DICT.get("name"),
        bool(_PLANNER_GUIDANCE),
        bool(user_token),
        _MLFLOW_ENABLED,
        _SSE_HEARTBEAT_SECONDS,
        _short_header(request, "x-shell-app-template-version"),
        _short_header(request, "accept"),
        _short_header(request, "user-agent"),
    )

    async def event_generator():
        event_count = 0
        # If enabled, wrap the run in a root MLflow span so framework spans
        # nest beneath one trace with ``dr.*`` provenance tags.
        span_cm = None
        if _MLFLOW_ENABLED:
            span_cm = mlflow.start_span(
                name=f"shell_app_chat.{_DR_APP_NAME or 'unknown'}"
            )
            try:
                span_cm.__enter__()
            except Exception as exc:  # pragma: no cover - defensive
                logger.warning(
                    "SHELL_APP_MLFLOW_SPAN_START_FAILED request_id=%s exc=%s",
                    request_id,
                    exc,
                )
                span_cm = None
        _set_dr_provenance_tags(
            query=str(query),
            workflow_id=str(getattr(_DEFINITION, "id", "") or ""),
            workflow_name=str(_DEFINITION_DICT.get("name", "") or ""),
        )
        # Only pass strict_tool_resolution to frameworks that accept it.
        # Older databricks-deep-research releases lack this kwarg; passing it
        # raises TypeError at runtime (see SHELL_APP_STREAM_KWARG_INCOMPATIBLE).
        # Production callers should opt in so factory misconfig (missing
        # index_name, dead workspace_client, etc.) raises WorkflowError
        # instead of being swallowed as a warning. The except-Exception
        # block below surfaces such errors as SSE error events for the UI.
        stream_kwargs: dict[str, Any] = {
            "workflow": _DEFINITION,
            "query": query,
        }
        if _SUPPORTS_STRICT_TOOL_RESOLUTION:
            stream_kwargs["strict_tool_resolution"] = True
        try:
            async for event in runner.stream(**stream_kwargs):
                event_count += 1
                if event_count <= 5 or event.event_type in {
                    "workflow_completed",
                    "error",
                }:
                    logger.info(
                        "SHELL_APP_STREAM_EVENT request_id=%s event_count=%s "
                        "event_type=%s node_id=%s",
                        request_id,
                        event_count,
                        event.event_type,
                        getattr(event, "node_id", None),
                    )
                # Surface tool failures at WARN. The framework's tools (VS,
                # Genie, etc.) return ToolResult(success=False) when
                # get_index discovery fails or query_index raises — without
                # this log line those failures are buried in the SSE stream
                # and the deployed surface looks the same as "0 sources
                # found", which made the original OBO bug invisible.
                if isinstance(event, ToolResultEvent) and not event.tool_success:
                    logger.warning(
                        "SHELL_APP_TOOL_FAILURE request_id=%s tool=%s "
                        "source_count=%s reason=%s",
                        request_id,
                        event.tool_name,
                        event.source_count,
                        (event.tool_error or "")[:300],
                    )
                yield {
                    "event": event.event_type,
                    "data": event.model_dump_json(),
                }
            result = runner.last_result
            sources = [
                _source_to_dict(s)
                for s in (result.sources[:10] if result else [])
            ]
            logger.info(
                "SHELL_APP_CHAT_COMPLETE request_id=%s event_count=%s "
                "output_length=%s source_count=%s",
                request_id,
                event_count,
                len(result.output if result else ""),
                len(sources),
            )
            yield {
                "event": "complete",
                "data": json.dumps(
                    {
                        "type": "complete",
                        "output": result.output if result else "",
                        "sources": sources,
                    }
                ),
            }
        except asyncio.CancelledError:
            logger.warning(
                "SHELL_APP_CHAT_CLIENT_DISCONNECTED request_id=%s event_count=%s",
                request_id,
                event_count,
            )
            raise
        except Exception as exc:  # noqa: BLE001 — surface to UI as 'error' event
            # Classify the exception so the UI can render an actionable
            # next-step instead of a raw Python error string. Phase 3 M4.
            error_kind = _classify_shell_app_exception(exc)
            logger.exception(
                "SHELL_APP_CHAT_ERROR request_id=%s event_count=%s "
                "exc_class=%s error_kind=%s",
                request_id,
                event_count,
                type(exc).__name__,
                error_kind,
            )
            yield {
                "event": "error",
                "data": json.dumps(
                    {
                        "type": "error",
                        "error_kind": error_kind,
                        "message": str(exc),
                        "exc_class": type(exc).__name__,
                    }
                ),
            }
        finally:
            # Close the root MLflow span. Mirrors __exit__ semantics so the
            # span is flushed even on error paths. Failures are swallowed —
            # we never want tracing cleanup to mask the real error.
            if span_cm is not None:
                trace_close_started = time.monotonic()
                try:
                    span_cm.__exit__(None, None, None)
                except Exception as exc:  # pragma: no cover - defensive
                    logger.warning(
                        "SHELL_APP_MLFLOW_SPAN_CLOSE_FAILED request_id=%s "
                        "elapsed_ms=%s exc=%s",
                        request_id,
                        int((time.monotonic() - trace_close_started) * 1000),
                        exc,
                    )
                else:
                    logger.info(
                        "SHELL_APP_MLFLOW_SPAN_CLOSED request_id=%s elapsed_ms=%s",
                        request_id,
                        int((time.monotonic() - trace_close_started) * 1000),
                    )
            logger.info(
                "SHELL_APP_CHAT_STREAM_CLOSED request_id=%s event_count=%s "
                "mlflow_enabled=%s",
                request_id,
                event_count,
                _MLFLOW_ENABLED,
            )

    return EventSourceResponse(
        event_generator(),
        headers={**_NO_STORE_HEADERS, "X-Shell-App-Request-Id": request_id},
        ping=_SSE_HEARTBEAT_SECONDS,
    )
