/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Databricks design system palette (additive — used by Agentic Designer UI)
        db: {
          white: "var(--db-white)",
          'oat-light': "var(--db-oat-light)",
          'oat-medium': "var(--db-oat-medium)",
          'lava-100': "var(--db-lava-100)",
          'lava-300': "var(--db-lava-300)",
          'lava-400': "var(--db-lava-400)",
          'lava-500': "var(--db-lava-500)",
          'lava-600': "var(--db-lava-600)",
          'lava-700': "var(--db-lava-700)",
          'lava-800': "var(--db-lava-800)",
          'navy-300': "var(--db-navy-300)",
          'navy-400': "var(--db-navy-400)",
          'navy-500': "var(--db-navy-500)",
          'navy-600': "var(--db-navy-600)",
          'navy-700': "var(--db-navy-700)",
          'navy-800': "var(--db-navy-800)",
          'navy-900': "var(--db-navy-900)",
          'gray-nav': "var(--db-gray-nav)",
          'gray-text': "var(--db-gray-text)",
          'gray-lines': "var(--db-gray-lines)",
          'green-300': "var(--db-green-300)",
          'green-400': "var(--db-green-400)",
          'green-500': "var(--db-green-500)",
          'green-600': "var(--db-green-600)",
          'green-700': "var(--db-green-700)",
          'green-800': "var(--db-green-800)",
          'yellow-300': "var(--db-yellow-300)",
          'yellow-400': "var(--db-yellow-400)",
          'yellow-500': "var(--db-yellow-500)",
          'yellow-600': "var(--db-yellow-600)",
          'yellow-700': "var(--db-yellow-700)",
          'yellow-800': "var(--db-yellow-800)",
          'blue-100': "var(--db-blue-100)",
          'blue-300': "var(--db-blue-300)",
          'blue-400': "var(--db-blue-400)",
          'blue-500': "var(--db-blue-500)",
          'blue-600': "var(--db-blue-600)",
          'blue-700': "var(--db-blue-700)",
          'blue-800': "var(--db-blue-800)",
          'maroon-300': "var(--db-maroon-300)",
          'maroon-400': "var(--db-maroon-400)",
          'maroon-500': "var(--db-maroon-500)",
          'maroon-600': "var(--db-maroon-600)",
          'maroon-700': "var(--db-maroon-700)",
          'maroon-800': "var(--db-maroon-800)",
        },
      },
      fontFamily: {
        'db-sans': ['"DM Sans"', 'ui-sans-serif', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Helvetica', 'Arial', 'sans-serif'],
        'db-mono': ['"DM Mono"', 'ui-monospace', '"SF Mono"', 'Menlo', 'Consolas', 'monospace'],
      },
      boxShadow: {
        'db-xs': '0 1px 2px rgba(11,32,38,0.06)',
        'db-sm': '0 1px 3px rgba(11,32,38,0.08), 0 1px 2px rgba(11,32,38,0.04)',
        'db-md': '0 4px 12px rgba(11,32,38,0.08), 0 1px 3px rgba(11,32,38,0.06)',
        'db-lg': '0 12px 32px rgba(11,32,38,0.12), 0 2px 6px rgba(11,32,38,0.06)',
        'db-xl': '0 24px 64px rgba(11,32,38,0.18)',
        'db-focus': '0 0 0 3px rgba(255, 54, 33, 0.28)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'db-md': '6px',
        'db-lg': '12px',
        'db-pill': '999px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
